### ISSUE TITLE
Carthage update failed with Cely/Cely

### ISSUE THREAD

**Issue by canatac** [chaione/Cely#16]
Hi,
When trying to update by :
`carthage update`
with 
`github "Cely/Cely" ~> 2.0.0`
in Cartfile

I got this response :
```
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/Cely/Cely.git /Users/xxx/Library/Caches/org.carthage.CarthageKit/dependencies/Cely) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
This works only with repo :
`github "chaione/Cely" ~> 2.0.0`

**Comment by initFabian** [comment]
Hey @canatac,

Thanks so much great find! Fork the repo and make PR to reflect your contribution!

**Comment by canatac** [comment]
@initFabian 
Done for this small contribution...

**Comment by initFabian** [comment]
Going to close this issue
