### ISSUE TITLE
Does Cely Support JWT?

### ISSUE THREAD

**Issue by rlam3** [chaione/Cely#18]
Does Cely Support JWT?

**Comment by initFabian** [comment]
Hey @rlam3,

Thanks for the Feedback!

You can use Cely to save a JWT. Now, are you talking about validating a JWT? If so, that responsibility would have to fall under a different class. Depending if the JWT is valid, you would simply call the methods `Cely.changeStatus(to: .loggedIn)` or `Cely.changeStatus(to: .loggedOut)` to switch the user between the login/home screen. 

Hope that made sense!

**Comment by rlam3** [comment]
@initFabian I'm looking for a way to manage the token where it is able to retrieve a new one if it expires...

To authenticate, I'm using user name and password and will recieve a access token and a refresh token. if the access token expires, it will try to use the refresh token to retrieve a new access and refresh token. 

Can Cely help with supporting this type of opperation? I'm currently using Moya to help with HTTP requests.

**Comment by initFabian** [comment]
Hey @rlam3 sorry for the delayed response. 

Unfortunately, Cely's purpose is not to handle anything responsibility with a network. You would continue using Moya to perform HTTP requests and use Cely to store the data.
