### ISSUE TITLE
I need help with swift 4 

### ISSUE THREAD

**Issue by edgcarmu** [chaione/Cely#22]
Hey, man, I need to upgrade one app which uses Cely for login and build in Xcode 9, Can you help me with that?

**Comment by initFabian** [comment]
Hey @edgcarmu, 

Thanks for catching this!

Where you getting an error similar to the error below?

```
error: redundant conformance constraint 'Self': 'SecureStorableResultType'
error: redundant conformance constraint 'U': 'RawRepresentable'
```

I just opened a PR #23, check it out and let me know if it fixes the problem. If you're using Carthage, just replace what's in your Cartfile with:
```
github "chaione/Cely" "fix-Swift-4-compiler-crash"
```

**Comment by edgcarmu** [comment]
Hey, man, it worked for me thanks a million!!

Could it be available too in cocoapods?

**Comment by initFabian** [comment]
Hey @edgcarmu,

The changes should apply to cocoapods, I just merged in the PR. Give it a shot and let me know.
