### ISSUE TITLE
Do we have a way to use Cley with RxSwift?

### ISSUE THREAD

**Issue by rlam3** [chaione/Cely#24]
Do we have a way to use Cley with RxSwift?

**Comment by initFabian** [comment]
Though I haven't personally tested Cely + reactive framework in an app, I don't see why they wouldn't work together. 

What type of issues are you running into?

**Comment by rlam3** [comment]
@initFabian I'd like to get your opinion on how to add the following Expirable protocol so I can manage tokens. 

https://github.com/AndrewSB/Expirable

This will enable us see which token expired or is expiring soon. So far following your example I don't know where I am able to enable the Expirable protocol

**Comment by initFabian** [comment]
Hey @rlam3 can you make a separate issue for the `Expirable`? 

I really do like the idea, I feel this feature falls within the scope of Cely, it just will need to be implemented differently. Open up a new issue and we can discuss it there.
