### ISSUE TITLE
Swift 4 and Xcode 9 is not supported? I'm still getting crashes. Would love to understand what the workaround might be for this is. Thanks!

### ISSUE THREAD

**Issue by rlam3** [chaione/Cely#25]
Swift 4 and Xcode 9 is not supported? I'm still getting crashes. Would love to understand what the workaround might be for this is. Thanks!

<img width="265" alt="screen shot 2017-11-06 at 3 26 36 pm" src="https://user-images.githubusercontent.com/1154044/32464843-0a6ab18a-c307-11e7-953b-ea2514597500.png">

**Comment by initFabian** [comment]
Hey @rlam3,

My bad. I forgot to release a tag for the Swift 4 Pr #23 . Tagged and pushed the swift 4 changes. Let me know if that fixes it.

**Comment by rlam3** [comment]
@initFabian It looks like cocoapods don't recognize or see this 2.0.1 version. Only 2.0.0. updating repo doesn't do anything either...

**Comment by rlam3** [comment]
@initFabian   
```
pod 'Cely', :git => 'https://github.com/chaione/Cely', :branch => 'master' 
```
also doesn't work

**Comment by initFabian** [comment]
Oh I see what the issue is. `Cely.podspec` was not updated to the correct version. Sorry, Im still learning how to mainstream all this type stuff. Going to reach out to a few friends on how they do it on their frameworks

**Comment by initFabian** [comment]
@rlam3 give it a shot now

**Comment by rlam3** [comment]
Looks good now 👍  Thanks! I'm new to this Cocoapod specs thing too. Closing issue now. 

Also to point out for those whom are moving away from swift 32. This is a better way of splitting up which cocoa pods which needs swift 3 or swift 4.

```ruby

swift_32 = []
swift4 = ['Cely']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    swift_version = nil

    if swift_32.include?(target.name)
      swift_version = '3.2'
    end

    if swift4.include?(target.name)
      swift_version = '4.0'
    end

    if swift_version
      target.build_configurations.each do |config|
        # config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        config.build_settings['SWIFT_VERSION'] = swift_version
    end

  end
end
end

```

**Comment by doronkatz** [comment]
Hi guys, is this related to #32 ? I am having issues and getting the error in #32 ..Thanks guys
