### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by nderkach** [chaione/Cely#26]
Hi,

thanks for this library! Do you have any plan to implement a signup flow as well, i.e. with a separate screen and a callback similar to `loginCompletionBlock`?

**Comment by initFabian** [comment]
Hey @nderkach, 

Adding signup screens would be tricky. especially since every app's signup process could be different. I'd recommend just creating you're own signup flow, save data on successful login, and calling `Cely.changeStatus(to: .loggedIn)`.

Would that work?

**Comment by nderkach** [comment]
I think that having a drop-in UI for a simple login/password sign up could be useful. And then, of course, you can extend to allowing login/signup via 3rd party providers like FB or Twitter.

Personally, I'm considering using `Cely` in combination with my custom UI. Considering that I'd have to implement all the UI including the signup screen from scratch, does it even make sense to use the library in this case?

**Comment by initFabian** [comment]
@nderkach absolutely!

The UI portion of an app's login/signup screens is fairly straightforward, and honestly, Cely's default login screen is mostly there only if you need something fast(30 sec or less). Where Cely's value comes to play is storing user's credentials securely(not just throw them in `UserDefaults`) and handling switching in-between login screen and your app's home screen correctly.

**Comment by nderkach** [comment]
I've ended up implementing my own custom solution this time. From my experience, creating the UI for login and signup was by far the most tedious and time-consuming part. Storing tokens/credentials and handling authentication state is simpler (one can simply use keychain for that).
