### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by luca-i** [chaione/Cely#9]
How should I do dependency injection?
Suppose I need to access an external service inside my login viewcontroller (the initial viewcontroller for loginStoryboard). The service is defined as a protocol.
I could use an implicitly unwrapped optional, but how could I set it?
Thank you, Luca-

**Comment by initFabian** [comment]
Hey @luca-i,

Been giving your issue some thought and am ready some more information. How are you currently instantiating your login viewcontroller? Should help us find a solution for your issue.

**Comment by luca-i** [comment]
Thank you @initFabian,
since the initial view controller is instantiated with Cely.setup static method, I can't inject any dependencies in it (i'm talking about something like https://www.natashatherobot.com/ios-view-controller-data-injection-with-storyboards-and-segues-in-swift/).

**Comment by initFabian** [comment]
Hey @luca-i,

Since Cely simply references the `rootViewController`, you should still have access to the loginVC. For example, you can still run code like this inside of your `AppDelegate`. 

```
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        Cely.setup(with: window, forModel: User(), requiredProperties: [User.Property.token], withOptions: [
            .loginStoryboard: UIStoryboard(name: "Login", bundle: nil)
        ])

        if let loginVC = window?.rootViewController as? MyCustomLoginViewController {
            loginVC.dependency = ...
        }
...
}
```

**Comment by initFabian** [comment]
Going to close this issue
